-- ---------------------------
-- CREATING DEFAULT OBJECTS
-- ---------------------------
CREATE ROLE AFTERSPOT_ETL_ROLE;
CREATE USER ETL PASSWORD = '******' DEFAULT_ROLE = "AFTERSPOT_ETL_ROLE";
CREATE USER BI PASSWORD = '******' DEFAULT_ROLE = "AFTERSPOT_ETL_ROLE";
CREATE WAREHOUSE AFTERSPOT_WH WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;
CREATE DATABASE AFTERSPOT_DB;
CREATE SCHEMA AFTERSPOT_DB.RAW_SCHEMA;
CREATE SCHEMA AFTERSPOT_DB.MARKETPLACES_SCHEMA;

-- ---------------------------
-- SESSION SETTINGS
-- ---------------------------
ALTER USER ETL SET QUOTED_IDENTIFIERS_IGNORE_CASE=TRUE;
ALTER USER BI SET QUOTED_IDENTIFIERS_IGNORE_CASE=TRUE;​

-- ---------------------------
-- GRANTS
-- ---------------------------
GRANT ROLE AFTERSPOT_ETL_ROLE TO USER ETL;
GRANT MODIFY, MONITOR, USAGE, CREATE SCHEMA ON DATABASE AFTERSPOT_DB TO AFTERSPOT_ETL_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE AFTERSPOT_DB TO ROLE AFTERSPOT_ETL_ROLE;
​
GRANT ALL ON ALL TABLES IN SCHEMA MARKETPLACES_SCHEMA TO ROLE AFTERSPOT_ETL_ROLE;
GRANT ALL ON ALL VIEWS IN SCHEMA MARKETPLACES_SCHEMA TO ROLE AFTERSPOT_ETL_ROLE;
GRANT ALL ON ALL TABLES IN SCHEMA RAW_SCHEMA TO ROLE AFTERSPOT_ETL_ROLE;
GRANT ALL ON ALL VIEWS IN SCHEMA RAW_SCHEMA TO ROLE AFTERSPOT_ETL_ROLE;
​
GRANT ALL ON FUTURE TABLES IN SCHEMA MARKETPLACES_SCHEMA TO ROLE AFTERSPOT_ETL_ROLE;
GRANT ALL ON FUTURE VIEWS IN SCHEMA MARKETPLACES_SCHEMA TO ROLE AFTERSPOT_ETL_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA RAW_SCHEMA TO ROLE AFTERSPOT_ETL_ROLE;
GRANT ALL ON FUTURE VIEWS IN SCHEMA RAW_SCHEMA TO ROLE AFTERSPOT_ETL_ROLE;
​
GRANT MONITOR, USAGE, CREATE TABLE, CREATE VIEW ON ALL SCHEMAS IN DATABASE AFTERSPOT_DB TO AFTERSPOT_ETL_ROLE;
